
export const ProfileProjectsConfig: any = {
  basisdollar: {
    title1: "Balance",
    key1: "farmingPools",
    title2: "Liquidity",
    key2: "sharePools",
    tokensKey1: "collateralTokens",
    tokensKey2: "collateralTokens",
    unclaimKey: "unclaimToken",
  },
  curve: {
    title1: "Farm",
    key1: "farmingPools",
    title2: "Liquidity",
    key2: "liquidityPools",
    tokensKey1: "stakedList",
    tokensKey2: "stakedList",
    unclaimKey: "rewardList",
  },
  yfii: {
    title1: "抵押",
    key1: "staking",
    title2: "Farm",
    key2: "liquidities",
    tokensKey1: "token",
    tokensKey2: "tokens",
    unclaimKey: "rewardToken",
  },
  cream: {
    title1: "Liquidity",
    key1: "liquidityPairInfos",
    tokensKey1: "collateralTokens",
    title2: "Farm",
    key2: "farmingPairInfos",
    tokensKey2: "collateralTokens",
    unclaimKey: "unclaimToken",
  },
  harvest: {
    title1: "Farm",
    key1: "stakePairInfos",
    tokensKey1: "collateralTokens",
    title2: "Vault",
    key2: "vaultPairInfos",
    tokensKey2: "collateralTokens",
    unclaimKey: "unclaimToken",
  },
  keeperdao: {
    title1: "Liquidity",
    key1: "pools",
    tokensKey1: "token",
    title2: "Farm",
    unclaimKey: "unclaimToken",
  },
  sushiswap: {
    title1: "Farm",
    key1: "farmingPools",
    tokensKey1: "collateralTokens",
    title2: "Liquidity",
    key2: "liquidityPools",
    tokensKey2: "collateralTokens",
    unclaimKey: "unclaimTokens",
  },
  badger: {
    title1: "Liquidity",
    key1: "settPairInfos",
    tokensKey1: "collateralTokens",
    title2: "Farm",
    key2: "stakePairInfos",
    tokensKey2: "collateralTokens",
    unclaimKey: "unclaimToken",
  },
  mooniswap: {
    title1: "Liquidity",
    key1: "liquidityPools",
    tokensKey1: "collateralTokens",
    title2: "Farm",
    unclaimKey: "unclaimTokens",
  },
  mithcash: {
    title1: "Liquidity",
    key1: "pools",
    tokensKey1: "tokens",
    title2: "Boardroom",
    // key2:"boardroom",
    // tokensKey2:"token",
    unclaimKey: "reward",
  },
  dodo: {
    title1: "Liquidity",
    key1: "liquidityPools",
    tokensKey1: "pairToken",
    title2: "Farm",
    key2: "farmingPools",
    tokensKey2: "pairToken",
    unclaimKey: "unclaimToken",
  },
  hegic: {
    title1: "Farm",
    key1: "stakingInfos",
    tokensKey1: "token",
    title2: "Balance",
    key2: "options",
    tokensKey2: "token",
    unclaimKey: "rewardToken",
  },
  uniswapv2: {
    title1: "UNIFarm",
    key1: "farmingPools",
    tokensKey1: "collateralTokens",
    title2: "V2",
    key2: "liquidityPools",
    tokensKey2: "collateralTokens",
    unclaimKey: "unclaimTokens",
  },
  powerindex: {
    title1: "Balance",
    key1: "pools",
    tokensKey1: "tokens",
    title2: "Liquidity",
    unclaimKey: "unclaimToken",
  },
  dusd: {
    title1: "Balance",
    // key1:"saving",
    // tokensKey1:"token",
    title2: "Farm",
    key2: "pools",
    tokensKey2: "tokens",
    unclaimKey: "reward",
  },
  barnbridge: {
    title1: "Balance",
    key1: "assets",
    tokensKey1: "token",
    title2: "Farm",
    key2: "pools",
    tokensKey2: "tokens",
    unclaimKey: "potentialReward",
  },
  bancor: {
    title1: "Liquidity",
    key1: "assets",
    tokensKey1: "tokens",
    title2: "protection",
    key2: "protection",
    tokensKey2: "tokens",
    unclaimKey: "potentialReward",
  },
  wepiggy: {
    title1: "Farm",
    key1: "pools",
    tokensKey1: "token",
    // title2:"protection",
    // key2:"protection",
    // tokensKey2:"tokens",
    unclaimKey: "reward",
  },
  balancer: {
    title1: "Liquidity",
    key1: "pools",
    tokensKey1: "tokens",
    title2: "protection",
    // key2:"protection",
    // tokensKey2:"tokens",
    unclaimKey: "reward",
  },
  dforce: {
    title1: "Uniswap",
    key1: "stakingPools",
    tokensKey1: "tokens",
    title2: "protection",
    // key2:"protection",
    // tokensKey2:"tokens",
    unclaimKey: "reward",
  },
  frax: {
    title1: "Balance",
    key1: "pools",
    tokensKey1: "tokens",
    title2: "protection",
    // key2:"protection",
    // tokensKey2:"tokens",
    unclaimKey: "reward",
  },
  pandayield: {
    title1: "Liquidity",
    key1: "pairs",
    tokensKey1: "tokens",
    title2: "Liquidity",
    key2: "liquidityPools",
    tokensKey2: "tokens",
    unclaimKey: "rewardToken",
  },
  alpaca: {
    title1: "Farm",
    key1: "liquidityPools",
    tokensKey1: "tokens",
    unclaimKey: "reward",
  },
  pancake: {
    title1: "Liquidity_V1",
    key1: "pairs",
    tokensKey1: "tokens",
    title2: "Liquidity",
    key2: "liquidityPools",
    tokensKey2: "tokens",
    unclaimKey: "rewardToken",
  },
  autofarmheco: {
    title1: "Liquidity",
    key1: "pools",
    tokensKey1: "tokens",
    unclaimKey: "reward",
  },
  goose: {
    title1: "Deposit",
    key1: "singlePools",
    tokensKey1: "tokens",
    title2: "Farm",
    key2: "liquidityPools",
    tokensKey2: "tokens",
    unclaimKey: "rewardToken",
  },
  bakeryswap: {
    title1: "Liquidity",
    key1: "liquidityPools",
    tokensKey1: "tokens",
    unclaimKey: "reward",
  },
  viking: {
    title1: "Liquidity",
    key1: "liquidityPools",
    tokensKey1: "tokens",
    title2: "Farm",
    key2: "pairs",
    tokensKey2: "tokens",
    unclaimKey: "rewardToken",
  },
  ellipsis: {
    title1: "Farm",
    key1: "farmingPools",
    tokensKey1: "collateralTokens",
    unclaimKey: "unclaimTokens",
  },
  ramenswap: {
    title1: "Liquidity",
    key1: "liquidityPools",
    tokensKey1: "tokens",
    title2: "Liquidity",
    key2: "farmPools",
    tokensKey2: "tokens",
    unclaimKey: "reward",
  },
  rabbit: {
    title1: "Farm",
    key1: "liquidityPools",
    tokensKey1: "tokens",
    unclaimKey: "reward",
  },
  bunny: {
    title1: "Farm",
    key1: "item",
    tokensKey1: "token",
    unclaimKey: "reward",
  },
  stormswap: {
    title1: "Liquidity",
    key1: "liquidityPools",
    tokensKey1: "tokens",
    title2: "Liquidity",
    key2: "farmPools",
    tokensKey2: "tokens",
    unclaimKey: "reward",
  },
  venus: {
    title1: "Farm",
    key1: "pools",
    tokensKey1: "token",
    unclaimKey: "reward",
  },
  pureswap: {
    title1: "Liquidity",
    key1: "liquidityPools",
    tokensKey1: "tokens",
    title2: "Liquidity",
    key2: "farmPools",
    tokensKey2: "tokens",
    unclaimKey: "reward",
  },
  julswap: {
    title1: "Farm",
    key1: "farmingPools",
    tokensKey1: "collateralTokens",
    unclaimKey: "unclaimTokens",
  },
  belt: {
    title1: "Farm",
    key1: "pools",
    tokensKey1: "tokens",
    unclaimKey: "rewardToken",
  },
  valuedefi: {
    title1: "Liquidity",
    key1: "liquidityPools",
    tokensKey1: "tokens",
    unclaimKey: "rewardToken",
  },
  ubu: {
    title1: "Farm",
    key1: "farmPools",
    tokensKey1: "tokens",
    title2: "UBANK",
    key2: "bankPools",
    tokensKey2: "tokens",
    unclaimKey: "reward",
  },
  "1inch": {
    title1: "Farm",
    key1: "liquidityPools",
    tokensKey1: "tokens",
    unclaimKey: "rewardToken",
  },
  btcst: {
    title1: "Farm",
    key1: "pools",
    tokensKey1: "tokens",
    unclaimKey: "rewardToken",
  },
  apeswap: {
    title1: "Liquidity",
    key1: "farmPools",
    tokensKey1: "farmTokens",
    unclaimKey: "rewardToken",
  },
  babyswap: {
    title1: "Liquidity",
    key1: "farmPools",
    tokensKey1: "farmTokens",
    unclaimKey: "rewardToken",
  },
  wault: {
    title1: "Liquidity",
    key1: "farmPools",
    tokensKey1: "farmTokens",
    title2: "Farm",
    key2: "stakePools",
    tokensKey2: "stakeToken",
    unclaimKey: "rewardToken",
  },
  definix: {
    title1: "Liquidity",
    key1: "liquidityPools",
    tokensKey1: "liquidityTokens",
    title2: "Liquidity",
    key2: "farmPools",
    tokensKey2: "farmTokens",
    unclaimKey: "rewardToken",
  },
  alitaswap: {
    title1: "Liquidity",
    key1: "farmPools",
    tokensKey1: "farmTokens",
    unclaimKey: "rewardToken",
  },
  pantherswap: {
    title1: "Liquidity",
    key1: "farmPools",
    tokensKey1: "farmTokens",
    unclaimKey: "rewardToken",
  },
  biswap: {
    title1: "Liquidity",
    key1: "liquidityPools",
    tokensKey1: "tokens",
    title2: "Liquidity",
    key2: "farmPools",
    tokensKey2: "tokens",
    unclaimKey: "reward",
  },
  warden: {
    title1: "Liquidity",
    key1: "farmPools",
    tokensKey1: "farmTokens",
    unclaimKey: "rewardToken",
  },
  nerve: {
    title1: "Liquidity",
    key1: "farmPools",
    tokensKey1: "farmTokens",
    unclaimKey: "rewardToken",
  },
  bdollar: {
    title1: "Farm",
    key1: "sharePools",
    tokensKey1: "tokens",
    unclaimKey: "reward",
  },
  mozert: {
    title1: "Farm",
    key1: "singlePools",
    tokensKey1: "tokens",
    unclaimKey: "rewardToken",
  },
  kimochi: {
    title1: "Deposit",
    key1: "liquidityPools",
    tokensKey1: "token",
    unclaimKey: "rewardToken",
  },
  supernova: {
    title1: "Bank",
    key1: "bankPools",
    tokensKey1: "tokens",
    title2: "Boardroom",
    key2: "daoPools",
    tokensKey2: "tokens",
    unclaimKey: "reward",
  },
  earndefi: {
    title1: "Deposit",
    key1: "pledges",
    tokensKey1: "tokens",
    title2: "Vault",
    key2: "smarts",
    tokensKey2: "tokens",
    unclaimKey: "reward",
  },
  bxh: {
    title1: "Farm",
    key1: "liquidityPools",
    tokensKey1: "tokens",
    title2: "DAO",
    key2: "boardPools",
    tokensKey2: "tokens",
    unclaimKey: "reward",
  },
  mdex: {
    title1: "Liquidity",
    key1: "farmingPools",
    tokensKey1: "collateralTokens",
    title2: "Liquidity",
    key2: "liquidityPools",
    tokensKey2: "collateralTokens",
    unclaimKey: "unclaimTokens",
  },
  filda: {
    title1: "Farm",
    key1: "stakings",
    tokensKey1: "tokens",
    unclaimKey: "reward",
  },
  hfi: {
    title1: "Deposit",
    key1: "stakingPools",
    tokensKey1: "tokens",
    title2: "Vault",
    key2: "vaultPools",
    tokensKey2: "tokens",
    unclaimKey: "reward",
  },
  converter: {
    title1: "Deposit",
    key1: "vaultPools",
    tokensKey1: "tokens",
    title2: "Farm",
    key2: "liquidityPools",
    tokensKey2: "tokens",
    unclaimKey: "reward",
  },
  coinwind: {
    title1: "Farm_V1",
    key1: "farmingPools",
    tokensKey1: "collateralTokens",
    title2: "Farm",
    key2: "farmingPools",
    tokensKey2: "collateralTokens",
    unclaimKey: "unclaimTokens",
  },
  newland: {
    title1: "Liquidity",
    key1: "pools",
    tokensKey1: "tokens",
    unclaimKey: "reward",
  },
  channels: {
    title1: "Liquidity",
    key1: "stakings",
    tokensKey1: "tokens",
    unclaimKey: "reward",
  },
  arkswap: {
    title1: "Liquidity",
    key1: "liquidityPools",
    tokensKey1: "collateralTokens",
    unclaimKey: "unclaimTokens",
  },
  lavaswap: {
    title1: "Farm_V1",
    key1: "farmingPools",
    tokensKey1: "collateralTokens",
    title2: "Liquidity",
    key2: "liquidityPools",
    tokensKey2: "collateralTokens",
    unclaimKey: "unclaimTokens",
  },
  basisgold: {
    title1: "Liquidity",
    key1: "pools",
    tokensKey1: "tokens",
    unclaimKey: "reward",
  },
  pippi: {
    title1: "Farm",
    key1: "farmingPools",
    tokensKey1: "collateralTokens",
    title2: "Liquidity",
    key2: "liquidityPools",
    tokensKey2: "collateralTokens",
    unclaimKey: "unclaimTokens",
  },
  lilithcash: {
    title1: "Farm",
    key1: "farmingPools",
    tokensKey1: "collateralTokens",
    unclaimKey: "unclaimTokens",
  },
  circleswap: {
    title1: "Liquidity",
    key1: "pools",
    tokensKey1: "tokens",
    title2: "Liquidity",
    key2: "miningPools",
    tokensKey2: "deposit",
    unclaimKey: "reward",
  },
  nftstk: {
    title1: "Farm",
    key1: "commonPool",
    tokensKey1: "tokens",
    unclaimKey: "reward",
  },
  starlink: {
    title1: "Farm",
    key1: "farmingPools",
    tokensKey1: "collateralTokens",
    unclaimKey: "unclaimTokens",
  },
  lendhub: {
    title1: "Farm",
    key1: "pools",
    tokensKey1: "tokens",
    unclaimKey: "reward",
  },
  depth: {
    title1: "Farm",
    key1: "pools",
    tokensKey1: "tokens",
    unclaimKey: "reward",
  },
  htmoon: {
    title1: "Liquidity",
    key1: "liquidityPools",
    tokensKey1: "collateralTokens",
    unclaimKey: "unclaimTokens",
  },
  pilot: {
    title1: "DAO",
    key1: "daoPools",
    tokensKey1: "tokens",
    unclaimKey: "rewardToken",
  },
  nfthero: {
    title1: "Farm",
    key1: "farmingPools",
    tokensKey1: "collateralTokens",
    unclaimKey: "unclaimTokens",
  },
  hbo: {
    title1: "Farm",
    key1: "farmingPools",
    tokensKey1: "collateralTokens",
    unclaimKey: "unclaimTokens",
  },
  hsswap: {
    title1: "Farm",
    key1: "liquidityPools",
    tokensKey1: "collateralTokens",
    unclaimKey: "unclaimTokens",
  },
  qidao: {
    title1: "Farm",
    key1: "farmingInfoList",
    tokensKey1: "supplyTokenList",
    unclaimKey: "rewardTokenList",
  },
  curvev3: {
    title1: "Liquidity",
    key1: "farmingPools",
    tokensKey1: "collateralTokens",
    title2: "UNIFarm",
    key2: "liquidityPools",
    tokensKey2: "collateralTokens",
    unclaimKey: "unclaimTokens",
  },
  dfyn: {
    title1: "Farm",
    key1: "farmingPools",
    tokensKey1: "collateralTokens",
    title2: "Liquidity",
    key2: "liquidityPools",
    tokensKey2: "collateralTokens",
    unclaimKey: "unclaimTokens",
  },
  balancerv2: {
    title1: "Liquidity",
    key1: "liquidityInfoList",
    tokensKey1: "supplyTokenList",
    unclaimKey: "rewardTokenList",
  },
};