import { BgImages } from "../../assets/bgImages/bgImages";

export const news = [
  {
    _id: "1",
    name:"media",
    publisher: "Medium",
    title: "Decentralized credit scores: How can blockchain tech change ratings",
    published: "April 24, 2022",
    picture: "https://images.cointelegraph.com/images/717_aHR0cHM6Ly9zMy5jb2ludGVsZWdyYXBoLmNvbS91cGxvYWRzLzIwMjItMDQvYjFkOTNlM2YtYWUzMi00Njg5LTkzNzYtMGIzMTkwZmJhZjBlLmpwZw==.jpg",
    url: "https://cointelegraph.com/news/decentralized-credit-scores-how-can-blockchain-tech-change-ratings",
    desc: "Borrowing and lending are two important parts of DeFi, but they have been missing an effective operating credential: a decentralized credit rating.The concept of lending and borrowing is as old as time itself. Regarding finances, while some individuals have more than enough for themselves, others barely have enough to get by. As long as there is this imbalance in finance distribution, there will always be a need to borrow and a desire to lend.",
  },
  {
    _id: "2",
    name:"media",
    publisher: "Medium",
    title: "Understanding and Undoing the Credit Paradox",
    published: "April 23, 2022",
    picture: "https://miro.medium.com/max/1400/1*6PKOcWig9P9oB-9zdu0WPw.png",
    url: "https://creda-app.medium.com/understanding-and-undoing-the-credit-paradox-6c05d5d3275d",
    desc: "I grew up as one of thirteen siblings in East London. Our parents were farming immigrants from Bangladesh. While I was growing up, I saw first-hand the challenges facing families who lacked an understanding of credit. Forced to live paycheck to paycheck, these families were unable to access traditional banking and therefor the opportunity to build creditworthiness.",
  },
  {
    _id: "3",
    name:"media",
    publisher: "Medium",
    title: "CreDA Credit Score protocol now available on Binance Smart Chain",
    published: "March 21, 2022",
    picture: "https://img.einnews.com/medium/285910/creda.jpeg",
    url: "https://www.einnews.com/pr_news/566077747/creda-credit-score-protocol-now-available-on-binance-smart-chain",
    desc: " CreDA (Credit Data Alliance), the leading decentralized credit rating service has launched on the Binance Smart Chain (BSC), allowing Web 3.0 and decentralized finance (DeFi) projects on the network to benefit from CreDA’s Crypto Credit Score. Hundreds of projects on BSC will now have the opportunity to use CreDA’s unique anonymized data to better target products and services while DeFi apps on the network can better manage risk and offer loans with lower rates and collateral requirements.",
  },
  {
    _id: "4",
    name:"media",
    publisher: "Medium",
    title: "5 Questions about CreDA’s partnership with Project Galaxy",
    published: "February 12, 2022",
    picture: "https://miro.medium.com/max/1400/1*-p5YgpUCW6FlG6JWWCIuiQ.png",
    url: "https://creda-app.medium.com/5-questions-about-credas-partnership-with-project-galaxy-3f5b83ce843b",
    desc: "Project Galaxy and CreDA are similar in that both projects are on a mission to build the infrastructure that will help ensure an open, honest and collaborative Web3.So we’re super excited to announce that we are partnering with Project Galaxy. But we know our community may be wondering how exactly the relationship will work.",
  },
  {
    _id: "5",
    name:"media",
    publisher: "einnews.com",
    title: "CreDA partners with CyberConnect to include social data in Crypto Credit Scores.",
    published: "February 04, 2022",
    picture: "https://images.cointelegraph.com/images/638_aHR0cHM6Ly9zMy5jb2ludGVsZWdyYXBoLmNvbS9zdG9yYWdlL3VwbG9hZHMvdmlldy8yZWY0OTE3MGMxZDQwMmUwZTQxYjM2NDMzNjUxMDg4Ni5qcGc=.jpg",
    url: "https://www.einnews.com/pr_news/562367246/creda-partners-with-cyberconnect-to-include-social-data-in-crypto-credit-scores",
    desc: "CreDA (Credit Data Alliance), the leading decentralized credit rating service and CyberConnect, the decentralized social graph protocol announced a partnership that will see CyberConnect’s 400,000+ users earn improved credit scores based on their social connections. Through the partnership, CreDA’s Credit Oracle will incorporate CyberConnect’s social graph data along with data found on users’ connected wallets, such as assets, risk profile and past on-chain behavior.",
  },
  {
    _id: "6",
    name:"media",
    publisher: "cointelegraph.com",
    title: "Former Morgan Stanley executive named new CreDA CEO",
    published: "January 24, 2022",
    picture: "https://images.cointelegraph.com/images/638_aHR0cHM6Ly9zMy5jb2ludGVsZWdyYXBoLmNvbS9zdG9yYWdlL3VwbG9hZHMvdmlldy8yZWY0OTE3MGMxZDQwMmUwZTQxYjM2NDMzNjUxMDg4Ni5qcGc=.jpg",
    url: "https://cointelegraph.com/press-releases/former-morgan-stanley-executive-named-new-creda-ceo",
    desc: "Credit Data Alliance (CreDA), the leading decentralized credit rating service, has announced the appointment of Fakhul Miah as the new CEO. Miah is leaving his position at Morgan Stanley in London, where he held key global and regional positions for 15 years, including titles such as global head of institutional margin financing, margin technology development and risk control.",
  },
  {
    _id: "7",
    name:"media",
    publisher: "finance.yahoo.com",
    title: "Crypto Credit Scoring Protocol CreDA Partners with FilDA to offer Leveraged and Low-Collateral Lending",
    published: "January 14, 2022",
    picture: "https://cryptomode.com/wp-content/uploads/2022/01/photo_2021-12-07_03-35-38-696x464.jpg",
    url: "https://finance.yahoo.com/news/crypto-credit-scoring-protocol-creda-023100330.html",
    desc: "CreDA is the world’s first decentralized credit rating service modeled after the traditional consumer credit agencies, providing users with a personal and secure crypto credit score. The objective of this blockchain-based rating system is to avail everyone the opportunity, the underbanked and unbanked, to access loans in the DeFi space without collateral. ",
  },
  {
    _id: "8",
    name:"media",
    publisher: "thecryptoupdates.com",
    title: "Is Alternative Credit Scoring the Solution for the Underbanked?",
    published: "January 14, 2022",
    picture: "https://cryptomode.com/wp-content/uploads/2022/01/photo_2021-12-07_03-35-38-696x464.jpg",
    url: "https://www.thecryptoupdates.com/is-alternative-credit-scoring-the-solution-for-the-underbanked/",
    desc: "CreDA is the world’s first decentralized credit rating service modeled after the traditional consumer credit agencies, providing users with a personal and secure crypto credit score. The objective of this blockchain-based rating system is to avail everyone the opportunity, the underbanked and unbanked, to access loans in the DeFi space without collateral. ",
  },
  {
    _id: "9",
    name:"media",
    publisher: "cryptomode.com",
    title: "CreDA: Prioritizing Financial Inclusivity",
    published: "January 12, 2022",
    picture: "https://cryptomode.com/wp-content/uploads/2022/01/photo_2021-12-07_03-35-38-696x464.jpg",
    url: "https://cryptomode.com/creda-prioritizing-financial-inclusivity/",
    desc: "CreDA is the world’s first decentralized credit rating service modeled after the traditional consumer credit agencies, providing users with a personal and secure crypto credit score. The objective of this blockchain-based rating system is to avail everyone the opportunity, the underbanked and unbanked, to access loans in the DeFi space without collateral. ",
  },
  {
    _id: "10",
    name:"media",
    publisher: "techbullion.com",
    title: "CreDA is Introducing Personal Credit Scores to Decentralized Finance",
    published: "January 12, 2022",
    picture: "https://cryptomode.com/wp-content/uploads/2022/01/photo_2021-12-07_03-35-38-696x464.jpg",
    url: "https://techbullion.com/creda-is-introducing-personal-credit-scores-to-decentralized-finance/",
    desc: "CreDA is the world’s first decentralized credit rating service modeled after the traditional consumer credit agencies, providing users with a personal and secure crypto credit score. The objective of this blockchain-based rating system is to avail everyone the opportunity, the underbanked and unbanked, to access loans in the DeFi space without collateral.",
  },
  {
    _id: "11",
    name:"media",
    publisher: "coincodex.com",
    title: "Creating a New Decentralized Finance Standard — The CreDa Vision",
    published: "January 12, 2022",
    picture: "https://miro.medium.com/max/1400/1*Q7462GoLoBbhX4ELXumcfQ.png",
    url: "https://coincodex.com/article/13384/creating-a-new-decentralized-finance-standard-the-creda-vision/",
    desc: "Your Crypto Credit Score is a number generated by your on-chain activity based on the wallet or wallets you connect to the CreDA Oracle. But it’s true power comes from the act of minting that number, along with your decentralized ID (DID) into a Credit NFT (cNFT).",
  },
  {
    _id: "12",
    name:"media",
    publisher: "Medium",
    title: "What is a credit NFT?",
    published: "December 29, 2021",
    picture: "https://miro.medium.com/max/1400/1*Q7462GoLoBbhX4ELXumcfQ.png",
    url: "https://creda-app.medium.com/what-is-a-credit-nft-f14b90542ed2",
    desc: "Your Crypto Credit Score is a number generated by your on-chain activity based on the wallet or wallets you connect to the CreDA Oracle. But it’s true power comes from the act of minting that number, along with your decentralized ID (DID) into a Credit NFT (cNFT).",
  },
  {
    _id: "13",
    publisher: "VoskCoin ",
    title: "",
    url: "https://www.youtube.com/embed/h_TSdsJtfoo?start=1022",
    published: "December 18, 2021",
  },
  {
    _id: "14",
    publisher: "Crypto Hustle",
    title: "",
    url: "https://www.youtube.com/embed/uL5-pH5a3mc?start=264",
    published: "November 29, 2021",
  },
  {
    _id: "15",
    name:"media",
    publisher: "AMB CRYPTO",
    title: "DeFi platform CreDA looks to de-risk the world of crypto",
    published: "November 25, 2021",
    url: "https://ambcrypto.com/defi-platform-creda-looks-to-de-risk-the-world-of-crypto/",
  },
  {
    _id: "16",
    name:"media",
    publisher: "yahoo!money",
    title: "New DeFI platform CreDA looks to de-risk the world of crypto",
    published: "November 25, 2021",
    url: "https://money.yahoo.com/defi-platform-creda-looks-risk-111700145.html",
  },
  {
    _id: "17",
    name:"media",
    publisher: "IHODL",
    title: "This Platform Uses AI to Power Credit Ratings for the DeFi Sector",
    published: "November 24, 2021",
    url: "https://ihodl.com/analytics/2021-11-24/platform-uses-ai-power-credit-ratings-defi-sector/",
  },
  {
    _id: "18",
    publisher: "Investing.com",
    name:"media",
    title:
      "CreDA Introduces Decentralized Credit Scoring to Boost Greater Access to Capital",
    published: "November 24, 2021",
    picture: "https://i-invdn-com.investing.com/news/LYNXNPEE1J1IK_L.jpg",
    url: "https://www.investing.com/news/cryptocurrency-news/creda-introduces-decentralized-credit-scoring-to-boost-greater-access-to-capital-2689328",
    desc: "CreDA (Credit Data Alliance), launches the world’s first decentralized credit service to improve the savings and loans system in crypto. The platform will use artificial intelligence (AI) systems to provide credit ratings using on-chain and traditional financial data.",
  },
];

export const press = [
  {
    _id: "1",
    publisherLogo: "https://picsum.photos/32",
    publisher: "Press Release",
    title: "CreDA partners with CyberConnect to include social data in Crypto Credit Scores ",
    published: "Feb 02, 2022 ",
    picture: `${BgImages.CyberConnect}`,
    desc:"CreDA (Credit Data Alliance), the leading decentralized credit rating service and CyberConnect, the decentralized social graph protocol announced a partnership that will see CyberConnect’s 400,000+ users earn improved credit scores based on their social connections. Through the partnership, CreDA’s Credit Oracle will incorporate CyberConnect’s social graph data along with data found on users’ connected wallets, such as assets, risk profile and past on-chain behavior. ",
    url:"/creda-partners-with-cyberconnect-to-include-social-data-in-crypto-credit-scores"
  },
  {
    _id: "2",
    publisherLogo: "https://picsum.photos/32",
    publisher: "Press Release",
    title: "Former Morgan Stanley Executive Named as New CreDA CEO",
    published: "Jan 20, 2022 ",
    picture: `${BgImages.FakhulMiah}`,
    url:"/former-morgan-stanley-executive-named-as-new-creda-ceo",
    desc:"CreDA (Credit Data Alliance), the leading decentralized credit rating service today announced the appointment of Fakhul Miah as the new Chief Executive Officer. Miah, leaves his position at Morgan Stanley in London, where he held key global and regional positions over 15 years including Global Head of Institutional Margin Financing, Margin Technology Development and Risk Control"
  },
  {
    _id: "3",
    publisherLogo: "https://picsum.photos/32",
    publisher: "Press Release",
    title: "Crypto Credit Scoring Protocol CreDA Partners with FilDA to offer Leveraged and Low-Collateral Lending",
    published: "Jan 10, 2022 ",
    picture: `${BgImages.CryptoScoringImages}`,
    url:"/crypto-credit-scoring-protocol-creda-partners-with-filda-to-offer-leveraged-and-low-collateral-lending",
    desc:"CreDA (Credit Data Alliance), the world's first decentralized credit rating service and FilDA, the largest ever DeFi lending platform on HECO with a peak TVL of over $2 billion USD, have partnered to offer exclusive lending rates to CreDA users. Users who mint their Crypto Credit Score as a Credit NFT (cNFT) will have access to leveraged lending and low or no-collateral loans directly within the CreDA platform."
  },
  {
    _id: "4",
    publisherLogo: "https://picsum.photos/32",
    publisher: "Press Release",
    title: "New DeFI platform looks to de-risk the world of crypto",
    published: "Nov 18, 2021 ",
    picture: "https://creda.stablewplite.com/static/media/pexels_olia_clean_low.2214235a.jpg",
    url:"new-defi-platform-looks-to-de-risk-the-world-of-crypto",
    desc:"CreDA (Credit Data Alliance), the world's first decentralized credit rating service has officially launched its platform following a successful open beta. Modeled after traditional consumer credit agencies, CreDA introduces the concept of personal credit scores into the $200 billion decentralized finance (DeFi) ecosystem populated by cryptocurrencies such as Bitcoin, Dogecoin and Ethereum.  "
  },
];

// export const influencers = [
  
  
// ];
